# Generated by Django 6.0 on 2025-12-29 09:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "عنوان", "verbose_name_plural": "العناوين"},
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "verbose_name": "ملف عميل",
                "verbose_name_plural": "ملفات العملاء",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "مستخدم", "verbose_name_plural": "المستخدمون"},
        ),
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("shipping", "عنوان شحن"), ("billing", "عنوان فواتير")],
                default="shipping",
                max_length=10,
                verbose_name="نوع العنوان",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="building",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="رقم المبنى/الوحدة"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=60, verbose_name="المدينة"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                default="Saudi Arabia", max_length=60, verbose_name="الدولة"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(blank=True, max_length=80, verbose_name="الحي"),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=120, verbose_name="الاسم الكامل"),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="افتراضي"),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="رقم الجوال"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="الرمز البريدي"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=120, verbose_name="الشارع"),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False, verbose_name="الموافقة على رسائل التسويق"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name="البريد الإلكتروني",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="الاسم الأول"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="موظف"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="اسم العائلة"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must be numeric and can start with +, length 7-15.",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="رقم الجوال",
            ),
        ),
    ]
